# Generated by Django 5.1 on 2024-08-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking_app.place')),
                ('reservant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking_app.user')),
            ],
        ),
    ]
