# Generated by Django 5.1 on 2024-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_place_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
